[mypy]
python_version = 3.12
mypy_path = python
ignore_missing_imports = True
disable_error_code = import-untyped
check_untyped_defs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True
show_error_codes = True

[mypy-tests.*]
check_untyped_defs = False
